Repository sonata-project/SonataBlockBundle, pull requests merged in 2018-11, with the labels that each got.

#510 Deprecate block assets
  UPGRADE-3.x.md
  src/Block/BlockServiceInterface.php
  src/Templating/Helper/BlockHelper.php
  tests/Templating/Helper/BlockHelperTest.php
Labels: minor

#512 Allow autowiring blocks
  src/DependencyInjection/Compiler/TweakCompilerPass.php
  tests/DependencyInjection/Compiler/TweakCompilerPassTest.php
Labels: patch

#517 Added some information about cache keys to the documentation
  docs/reference/cache.rst
Labels: docs

#519 updated bootstrap.php file
  tests/bootstrap.php
Labels: pedantic
