Repository sonata-project/SonataBlockBundle, pull requests merged in 2019-08, with the labels that each got.

#616 Added support for PHPUnit 8
  src/Test/BlockServiceTestCase.php
Labels: patch

#619 Fixed validation of EditableBlocks
  src/Block/BlockServiceManager.php
Labels: patch

#622 Use Twig namespaced classes
  tests/Twig/Extension/BlockExtensionTest.php
Labels: pedantic

#621 Deprecate "sonata.templating" service
  src/Block/Service/AbstractBlockService.php
  src/Resources/config/core.xml
  src/Test/BlockServiceTestCase.php
  src/Test/FakeTemplating.php
  tests/Block/Service/CustomBlockServiceTest.php
  tests/Block/Service/EmptyBlockServiceTest.php
  tests/Block/Service/MenuBlockServiceTest.php
  tests/Block/Service/RssBlockServiceTest.php
  tests/Block/Service/TextBlockServiceTest.php
  tests/Test/FakeTemplatingTest.php
Labels: minor

#626 Remove default image from metadata
  src/Meta/Metadata.php
Labels: minor

#625 Fix auto-registration of tagged blocks
  src/DependencyInjection/Compiler/TweakCompilerPass.php
  src/DependencyInjection/SonataBlockExtension.php
  tests/DependencyInjection/Compiler/TweakCompilerPassTest.php
Labels: patch

#614 Update BlockHelper.php
  src/Templating/Helper/BlockHelper.php
  tests/Templating/Helper/BlockHelperTest.php
Labels: minor
