Repository sonata-project/SonataBlockBundle, pull requests merged in 2019-07, with the labels that each got.

#584 Fix argument 1 passed to `DebugBlocksCommand::__construct()` at `commands.xml`
  src/Resources/config/commands.xml
Labels: bug, patch

#595 Remove superfluous docblocks
  src/Annotation/Block.php
  src/Block/BlockContext.php
  src/Block/BlockContextManager.php
  src/Block/BlockContextManagerInterface.php
  src/Block/BlockRenderer.php
  src/Block/BlockRendererInterface.php
  src/Block/BlockServiceInterface.php
  src/Block/BlockServiceManager.php
  src/Block/BlockServiceManagerInterface.php
  src/Block/Service/AbstractAdminBlockService.php
  src/Block/Service/AbstractBlockService.php
  src/Block/Service/AdminBlockServiceInterface.php
  src/Block/Service/MenuBlockService.php
  src/Cache/HttpCacheHandlerInterface.php
  src/DependencyInjection/Compiler/TweakCompilerPass.php
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SonataBlockExtension.php
  src/Event/BlockEvent.php
  src/Event/TextBlockListener.php
  src/Exception/Strategy/StrategyManager.php
  src/Form/Type/ContainerTemplateType.php
  src/Form/Type/ServiceListType.php
  src/Menu/MenuBuilderInterface.php
  src/Templating/Helper/BlockHelper.php
  src/Twig/Extension/BlockExtension.php
  tests/Exception/Filter/KeepAllFilterTest.php
  tests/Exception/Filter/KeepNoneFilterTest.php
  tests/Exception/Strategy/StrategyManagerTest.php
Labels: pedantic

#593 Closing tests
  tests/Block/BlockContextManagerTest.php
  tests/Block/BlockExecutionContextTest.php
  tests/Block/BlockLoaderChainTest.php
  tests/Block/BlockRendererTest.php
  tests/Block/BlockServiceManagerTest.php
  tests/Block/Loader/ServiceLoaderTest.php
  tests/Block/Service/MenuBlockServiceTest.php
  tests/Block/Service/RssBlockServiceTest.php
  tests/Block/Service/TextBlockServiceTest.php
  tests/Cache/HttpCacheHandlerTest.php
  tests/Cache/NoopHttpCacheHandlerTest.php
  tests/Command/DebugBlocksCommandTest.php
  tests/DependencyInjection/Compiler/AnnotationCompilerPassTest.php
  tests/DependencyInjection/ConfigurationTest.php
  tests/Event/BlockEventTest.php
  tests/Event/TextBlockListenerTest.php
  tests/Exception/Filter/DebugOnlyFilterTest.php
  tests/Exception/Filter/IgnoreClassFilterTest.php
  tests/Exception/Filter/KeepAllFilterTest.php
  tests/Exception/Filter/KeepNoneFilterTest.php
  tests/Exception/Renderer/InlineDebugRendererTest.php
  tests/Exception/Renderer/InlineRendererTest.php
  tests/Exception/Renderer/MonkeyThrowRendererTest.php
  tests/Exception/Strategy/StrategyManagerTest.php
  tests/Fixtures/Block/FooBlock.php
  tests/Form/Type/ServiceListTypeTest.php
  tests/Model/BlockTest.php
  tests/Naming/ConvertFromFqcnTest.php
  tests/Resources/XliffTest.php
  tests/Templating/Helper/BlockHelperTest.php
  tests/Test/FakeTemplatingTest.php
  tests/Twig/Extension/BlockExtensionTest.php
  tests/Twig/GlobalVariablesTest.php
  tests/Util/RecursiveBlockIteratorIteratorTest.php
Labels: pedantic

#589 Deprecated JMS annotations
  docs/reference/annotations.rst
  src/Annotation/Block.php
Labels: minor

#594 Add "@final" and "@internal" annotations
  src/Annotation/Block.php
  src/Block/BlockContext.php
  src/Block/BlockContextManager.php
  src/Block/BlockLoaderChain.php
  src/Block/BlockRenderer.php
  src/Block/BlockServiceManager.php
  src/Block/Loader/ServiceLoader.php
  src/Block/Service/ContainerBlockService.php
  src/Block/Service/EmptyBlockService.php
  src/Block/Service/MenuBlockService.php
  src/Block/Service/RssBlockService.php
  src/Block/Service/TemplateBlockService.php
  src/Block/Service/TextBlockService.php
  src/Cache/HttpCacheHandler.php
  src/Cache/NoopHttpCacheHandler.php
  src/Command/DebugBlocksCommand.php
  src/DependencyInjection/Compiler/GlobalVariablesCompilerPass.php
  src/DependencyInjection/Compiler/TweakCompilerPass.php
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SonataBlockExtension.php
  src/Event/BlockEvent.php
  src/Exception/BlockNotFoundException.php
  src/Exception/BlockOptionsException.php
  src/Exception/Filter/DebugOnlyFilter.php
  src/Exception/Filter/IgnoreClassFilter.php
  src/Exception/Filter/KeepAllFilter.php
  src/Exception/Filter/KeepNoneFilter.php
  src/Exception/Renderer/InlineDebugRenderer.php
  src/Exception/Renderer/InlineRenderer.php
  src/Exception/Renderer/MonkeyThrowRenderer.php
  src/Exception/Strategy/StrategyManager.php
  src/Form/Type/ContainerTemplateType.php
  src/Form/Type/ServiceListType.php
  src/Meta/Metadata.php
  src/Model/EmptyBlock.php
  src/Profiler/DataCollector/BlockDataCollector.php
  src/SonataBlockBundle.php
  src/Templating/Helper/BlockHelper.php
  src/Twig/Extension/BlockExtension.php
  src/Twig/GlobalVariables.php
  src/Util/RecursiveBlockIterator.php
Labels: minor

#591 Use symfony contracts
  composer.json
  src/Event/BlockEvent.php
  src/Templating/Helper/BlockHelper.php
  tests/Templating/Helper/BlockHelperTest.php
Labels: major

#592 Drop support for old versions
  composer.json
Labels: major

#579 Closing API
  UPGRADE-4.0.md
  src/Block/BlockContext.php
  src/Block/BlockContextManager.php
  src/Block/BlockLoaderChain.php
  src/Block/BlockRenderer.php
  src/Block/BlockServiceManager.php
  src/Block/Loader/ServiceLoader.php
  src/Block/Service/ContainerBlockService.php
  src/Block/Service/EmptyBlockService.php
  src/Block/Service/MenuBlockService.php
  src/Block/Service/RssBlockService.php
  src/Block/Service/TemplateBlockService.php
  src/Block/Service/TextBlockService.php
  src/Cache/HttpCacheHandler.php
  src/Cache/NoopHttpCacheHandler.php
  src/Command/DebugBlocksCommand.php
  src/DependencyInjection/Compiler/GlobalVariablesCompilerPass.php
  src/DependencyInjection/Compiler/TweakCompilerPass.php
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SonataBlockExtension.php
  src/Event/BlockEvent.php
  src/Exception/BlockNotFoundException.php
  src/Exception/BlockOptionsException.php
  src/Exception/Filter/DebugOnlyFilter.php
  src/Exception/Filter/IgnoreClassFilter.php
  src/Exception/Filter/KeepAllFilter.php
  src/Exception/Filter/KeepNoneFilter.php
  src/Exception/Renderer/InlineDebugRenderer.php
  src/Exception/Renderer/InlineRenderer.php
  src/Exception/Renderer/MonkeyThrowRenderer.php
  src/Exception/Strategy/StrategyManager.php
  src/Form/Type/ContainerTemplateType.php
  src/Form/Type/ServiceListType.php
  src/Meta/Metadata.php
  src/Model/EmptyBlock.php
  src/Profiler/DataCollector/BlockDataCollector.php
  src/SonataBlockBundle.php
  src/Templating/Helper/BlockHelper.php
  src/Twig/Extension/BlockExtension.php
  src/Twig/GlobalVariables.php
  src/Util/RecursiveBlockIterator.php
  src/Util/RecursiveBlockIteratorIterator.php
Labels: major

#601 Fix version at "@internal" annotations
  src/Templating/Helper/BlockHelper.php
Labels: patch

#604 Deprecated BaseCommand
  src/Command/BaseCommand.php
Labels: minor

#587 Deprecated AbstractBlockServiceTestCase class with BlockServiceTestCase
  src/Test/AbstractBlockServiceTestCase.php
  src/Test/BlockServiceTestCase.php
  tests/Block/Service/MenuBlockServiceTest.php
  tests/Block/Service/RssBlockServiceTest.php
  tests/Block/Service/TextBlockServiceTest.php
Labels: minor

#608 Removed inheritdoc
  src/Block/BlockContext.php
  src/Block/BlockContextManager.php
  src/Block/BlockLoaderChain.php
  src/Block/BlockRenderer.php
  src/Block/BlockServiceManager.php
  src/Block/Loader/ServiceLoader.php
  src/Block/Service/AbstractAdminBlockService.php
  src/Block/Service/AbstractBlockService.php
  src/Block/Service/ContainerBlockService.php
  src/Block/Service/EmptyBlockService.php
  src/Block/Service/MenuBlockService.php
  src/Block/Service/RssBlockService.php
  src/Block/Service/TemplateBlockService.php
  src/Block/Service/TextBlockService.php
  src/Cache/HttpCacheHandler.php
  src/Cache/NoopHttpCacheHandler.php
  src/Command/DebugBlocksCommand.php
  src/DependencyInjection/Compiler/GlobalVariablesCompilerPass.php
  src/DependencyInjection/Compiler/TweakCompilerPass.php
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SonataBlockExtension.php
  src/Exception/Filter/DebugOnlyFilter.php
  src/Exception/Filter/IgnoreClassFilter.php
  src/Exception/Filter/KeepAllFilter.php
  src/Exception/Filter/KeepNoneFilter.php
  src/Exception/Renderer/InlineDebugRenderer.php
  src/Exception/Renderer/InlineRenderer.php
  src/Exception/Renderer/MonkeyThrowRenderer.php
  src/Exception/Strategy/StrategyManager.php
  src/Form/Type/ContainerTemplateType.php
  src/Form/Type/ServiceListType.php
  src/Menu/MenuRegistry.php
  src/Model/BaseBlock.php
  src/Model/Block.php
  src/Profiler/DataCollector/BlockDataCollector.php
  src/SonataBlockBundle.php
  src/Templating/Helper/BlockHelper.php
  src/Test/FakeTemplating.php
  src/Twig/Extension/BlockExtension.php
  src/Util/RecursiveBlockIterator.php
Labels: pedantic

#612 Remove some superfluous docblocks
  src/Block/BlockRenderer.php
  src/Block/BlockServiceInterface.php
  src/Block/Service/AbstractBlockService.php
  src/Cache/HttpCacheHandlerInterface.php
  src/Form/Mapper/FormMapper.php
  src/Model/BlockInterface.php
  src/Templating/Helper/BlockHelper.php
Labels: pedantic

#562 Extend symfony DataCollector, do not serialize created_at as \DateTime
  src/Profiler/DataCollector/BlockDataCollector.php
  src/Templating/Helper/BlockHelper.php
  tests/Profiler/DataCollector/BlockDataCollectorTest.php
Labels: bug, patch

#610 Use explicit API
  src/Block/BlockContext.php
  src/Block/BlockContextInterface.php
  src/Block/BlockContextManager.php
  src/Block/BlockContextManagerInterface.php
  src/Block/BlockLoaderChain.php
  src/Block/BlockLoaderInterface.php
  src/Block/BlockRenderer.php
  src/Block/BlockRendererInterface.php
  src/Block/BlockServiceManager.php
  src/Block/BlockServiceManagerInterface.php
  src/Block/Loader/ServiceLoader.php
  src/Block/Service/AbstractBlockService.php
  src/Block/Service/BlockServiceInterface.php
  src/Block/Service/ContainerBlockService.php
  src/Block/Service/EditableBlockService.php
  src/Block/Service/EmptyBlockService.php
  src/Block/Service/MenuBlockService.php
  src/Block/Service/RssBlockService.php
  src/Block/Service/TemplateBlockService.php
  src/Block/Service/TextBlockService.php
  src/Cache/HttpCacheHandler.php
  src/Cache/HttpCacheHandlerInterface.php
  src/Cache/NoopHttpCacheHandler.php
  src/Command/BaseCommand.php
  src/Event/BlockEvent.php
  src/Exception/Filter/DebugOnlyFilter.php
  src/Exception/Filter/FilterInterface.php
  src/Exception/Filter/IgnoreClassFilter.php
  src/Exception/Filter/KeepAllFilter.php
  src/Exception/Filter/KeepNoneFilter.php
  src/Exception/Renderer/InlineDebugRenderer.php
  src/Exception/Renderer/InlineRenderer.php
  src/Exception/Renderer/MonkeyThrowRenderer.php
  src/Exception/Renderer/RendererInterface.php
  src/Exception/Strategy/StrategyManager.php
  src/Exception/Strategy/StrategyManagerInterface.php
  src/Form/Mapper/FormMapper.php
  src/Menu/MenuRegistry.php
  src/Menu/MenuRegistryInterface.php
  src/Meta/Metadata.php
  src/Meta/MetadataInterface.php
  src/Model/BaseBlock.php
  src/Model/BlockInterface.php
  src/Profiler/DataCollector/BlockDataCollector.php
  src/Templating/Helper/BlockHelper.php
  tests/Block/BlockRendererTest.php
Labels: major
