Repository sonata-project/SonataBlockBundle, pull requests merged in 2022-10, with the labels that each got.

#1122 Add support for doctrine/collections 2
  composer.json
Labels: minor

#1124 Menu parameter as required
  src/Block/Service/MenuBlockService.php
  tests/Block/Service/MenuBlockServiceTest.php
Labels: patch

#1121 Fix init of block settings
  src/Block/BlockContextManager.php
  tests/Block/BlockContextManagerTest.php
Labels: bug, patch
