Repository sonata-project/SonataBlockBundle, pull requests merged in 2022-03, with the labels that each got.

#1025 fix phpstan/psalm errors
  src/DependencyInjection/Compiler/TweakCompilerPass.php
  src/DependencyInjection/SonataBlockExtension.php
  src/Form/Type/ServiceListType.php
Labels: pedantic

#1027 Bump phpstan to level 8
  phpstan.neon.dist
  src/Block/BlockContext.php
  src/Block/BlockContextManager.php
  src/Block/BlockRenderer.php
  src/Block/BlockServiceManager.php
  src/Block/Service/AbstractBlockService.php
  src/Block/Service/ContainerBlockService.php
  src/Block/Service/MenuBlockService.php
  src/Block/Service/RssBlockService.php
  src/Block/Service/TemplateBlockService.php
  src/Block/Service/TextBlockService.php
  src/Command/DebugBlocksCommand.php
  src/DependencyInjection/Compiler/TweakCompilerPass.php
  src/DependencyInjection/SonataBlockExtension.php
  src/Exception/Strategy/StrategyManager.php
  src/Model/BaseBlock.php
  src/Model/Block.php
  src/Model/BlockInterface.php
  src/Templating/Helper/BlockHelper.php
  tests/Block/BlockContextManagerTest.php
  tests/Block/BlockServiceManagerTest.php
  tests/Resources/XliffValidatorTestCase.php
  tests/Templating/Helper/BlockHelperTest.php
  tests/Twig/Extension/BlockExtensionTest.php
Labels: pedantic

#1011 Deprecate caching related functionality
  UPGRADE-4.x.md
  composer.json
  src/Block/BlockContextManager.php
  src/Cache/HttpCacheHandler.php
  src/Cache/HttpCacheHandlerInterface.php
  src/Cache/NoopHttpCacheHandler.php
  src/DependencyInjection/Compiler/BlockHelperCompilerPass.php
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SonataBlockExtension.php
  src/Model/BaseBlock.php
  src/Model/BlockInterface.php
  src/Resources/config/core.xml
  src/SonataBlockBundle.php
  src/Templating/Helper/BlockHelper.php
  src/Test/BlockServiceTestCase.php
  tests/App/config.yml
  tests/Block/BlockContextManagerTest.php
  tests/DependencyInjection/ConfigurationTest.php
  tests/DependencyInjection/SonataBlockExtensionTest.php
  tests/Templating/Helper/BlockHelperTest.php
Labels: minor, enhancement

#1026 Allow blockContext without template
  src/Block/BlockContext.php
  src/Block/BlockContextManager.php
Labels: patch

#1029 Prepare to run symfony lints
  tests/App/AppKernel.php
Labels: pedantic

#1030 Convert config from xml to php
  src/DependencyInjection/SonataBlockExtension.php
  src/Resources/config/block.php
  src/Resources/config/block.xml
  src/Resources/config/commands.php
  src/Resources/config/commands.xml
  src/Resources/config/core.php
  src/Resources/config/core.xml
  src/Resources/config/exception.php
  src/Resources/config/exception.xml
  src/Resources/config/form.php
  src/Resources/config/form.xml
  src/Resources/config/knp_block.php
  src/Resources/config/knp_block.xml
Labels: pedantic
