Repository sonata-project/SonataBlockBundle, pull requests merged in 2022-04, with the labels that each got.

#1042 more caching related deprecations
  src/Model/BaseBlock.php
  src/Resources/config/core.php
  src/Templating/Helper/BlockHelper.php
  tests/Templating/Helper/BlockHelperTest.php
Labels: minor, enhancement

#1041 start cleaning up deprecated caching functionality
  src/Block/BlockContextManager.php
  src/DependencyInjection/Compiler/BlockHelperCompilerPass.php
  src/Model/BaseBlock.php
  src/Resources/config/core.php
  src/Resources/views/Profiler/block.html.twig
  src/SonataBlockBundle.php
  src/Templating/Helper/BlockHelper.php
  src/Test/BlockServiceTestCase.php
  tests/Block/BlockContextManagerTest.php
  tests/Templating/Helper/BlockHelperTest.php
Labels: major

#1045 more missing deprecations for caching functionality
  src/Block/Service/AbstractBlockService.php
  src/Block/Service/MenuBlockService.php
Labels: minor

#1044 Remove all caching related functionality
  composer.json
  src/Block/BlockRenderer.php
  src/Block/Service/AbstractBlockService.php
  src/Block/Service/MenuBlockService.php
  src/Cache/HttpCacheHandler.php
  src/Cache/HttpCacheHandlerInterface.php
  src/Cache/NoopHttpCacheHandler.php
  src/DependencyInjection/Compiler/TweakCompilerPass.php
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SonataBlockExtension.php
  src/Model/BaseBlock.php
  src/Model/BlockInterface.php
  src/Resources/config/core.php
  src/Resources/translations/SonataBlockBundle.de.xliff
  src/Resources/translations/SonataBlockBundle.en.xliff
  src/Resources/translations/SonataBlockBundle.fr.xliff
  src/Resources/translations/SonataBlockBundle.hu.xliff
  src/Resources/translations/SonataBlockBundle.it.xliff
  src/Resources/translations/SonataBlockBundle.nl.xliff
  tests/App/config.yml
  tests/Block/Service/MenuBlockServiceTest.php
  tests/Cache/HttpCacheHandlerTest.php
  tests/Cache/NoopHttpCacheHandlerTest.php
  tests/DependencyInjection/ConfigurationTest.php
  tests/DependencyInjection/SonataBlockExtensionTest.php
  tests/Model/BlockTest.php
Labels: major

#1050 resolve NEXT_MAJOR comments
  src/Block/BlockContext.php
  src/Block/BlockContextInterface.php
  src/Block/BlockContextManager.php
  src/Block/BlockContextManagerInterface.php
  src/Block/Service/AbstractBlockService.php
  src/Block/Service/ContainerBlockService.php
  src/Block/Service/MenuBlockService.php
  src/Block/Service/RssBlockService.php
  src/Block/Service/TemplateBlockService.php
  src/Block/Service/TextBlockService.php
  src/DependencyInjection/Compiler/TweakCompilerPass.php
  src/DependencyInjection/SonataBlockExtension.php
  src/Model/BaseBlock.php
  src/Test/BlockServiceTestCase.php
  tests/DependencyInjection/ConfigurationTest.php
Labels: major

#1051 use service locator within BlockServiceManager
  src/Block/BlockServiceManager.php
  src/Block/BlockServiceManagerInterface.php
  src/DependencyInjection/Compiler/TweakCompilerPass.php
  src/Resources/config/core.php
  tests/Block/BlockServiceManagerTest.php
Labels: minor

#1054 resolve NEXT_MAJOR comments
  src/Block/BlockServiceManager.php
  src/DependencyInjection/Compiler/TweakCompilerPass.php
  tests/Block/BlockServiceManagerTest.php
Labels: major

#1056 Cleanup deprecated class
  composer.json
  src/Model/BlockManagerInterface.php
Labels: major

#1059 Remove unused dependency
  composer.json
Labels: pedantic

#1052 Increase PHPStan and Psalm
  composer.json
  phpstan.neon.dist
  psalm.xml
  src/DependencyInjection/Configuration.php
  src/Exception/Renderer/InlineDebugRenderer.php
  src/Form/Type/ServiceListType.php
  src/Templating/Helper/BlockHelper.php
  tests/App/AppKernel.php
Labels: pedantic
