Repository sonata-project/SonataBlockBundle, pull requests merged in 2022-05, with the labels that each got.

#1057 Add Rector configuration
  .gitattributes
  .github/workflows/qa.yaml
  Makefile
  composer.json
  rector.php
  src/Block/BlockContext.php
  src/Block/BlockContextManager.php
  src/Block/BlockLoaderChain.php
  src/Block/BlockRenderer.php
  src/Block/BlockServiceManager.php
  src/Block/Loader/ServiceLoader.php
  src/Block/Service/AbstractBlockService.php
  src/Block/Service/MenuBlockService.php
  src/Cache/HttpCacheHandler.php
  src/Command/DebugBlocksCommand.php
  src/DependencyInjection/Configuration.php
  src/Event/BlockEvent.php
  src/Exception/Filter/DebugOnlyFilter.php
  src/Exception/Filter/IgnoreClassFilter.php
  src/Exception/Renderer/InlineDebugRenderer.php
  src/Exception/Renderer/InlineRenderer.php
  src/Exception/Strategy/StrategyManager.php
  src/Form/Type/ContainerTemplateType.php
  src/Form/Type/ServiceListType.php
  src/Menu/MenuRegistry.php
  src/Meta/Metadata.php
  src/Profiler/DataCollector/BlockDataCollector.php
  src/Templating/Helper/BlockHelper.php
  src/Twig/GlobalVariables.php
  tests/Block/BlockRendererTest.php
  tests/Command/DebugBlocksCommandTest.php
  tests/DependencyInjection/Compiler/TweakCompilerPassTest.php
  tests/Exception/Strategy/StrategyManagerTest.php
  tests/Templating/Helper/BlockHelperTest.php
  tests/Twig/Extension/BlockExtensionTest.php
Labels: pedantic

#1064 Upgrade to PHP 8 as minimum version
  .github/workflows/test.yaml
  composer.json
  rector.php
  src/Block/BlockContext.php
  src/Block/BlockContextManager.php
  src/Block/BlockLoaderChain.php
  src/Block/BlockRenderer.php
  src/Block/BlockServiceManager.php
  src/Block/Loader/ServiceLoader.php
  src/Block/Service/AbstractBlockService.php
  src/Block/Service/ContainerBlockService.php
  src/Block/Service/MenuBlockService.php
  src/Block/Service/RssBlockService.php
  src/Command/DebugBlocksCommand.php
  src/DependencyInjection/Configuration.php
  src/Event/BlockEvent.php
  src/Exception/Filter/DebugOnlyFilter.php
  src/Exception/Filter/IgnoreClassFilter.php
  src/Exception/Renderer/InlineDebugRenderer.php
  src/Exception/Renderer/InlineRenderer.php
  src/Exception/Strategy/StrategyManager.php
  src/Form/Type/ContainerTemplateType.php
  src/Form/Type/ServiceListType.php
  src/Meta/Metadata.php
  src/Model/BaseBlock.php
  src/Profiler/DataCollector/BlockDataCollector.php
  src/Templating/Helper/BlockHelper.php
  src/Twig/GlobalVariables.php
Labels: major

#1069 Fix psalm
  src/Templating/Helper/BlockHelper.php
Labels: pedantic

#1068 Deprecate FormMapper::create
  src/Form/Mapper/FormMapper.php
Labels: minor

#1076 Add typehint in doc
  docs/reference/testing.rst
  docs/reference/your_first_block.rst
Labels: docs
