Repository sonata-project/SonataBlockBundle, pull requests merged in 2022-07, with the labels that each got.

#1086 Update rector
  composer.json
Labels: pedantic

#1087 Allow to use collection for block childrens
  src/Model/BaseBlock.php
  src/Model/BlockInterface.php
  src/Util/RecursiveBlockIterator.php
Labels: minor

#1090 Avoid hasChildren deprecation
  src/Model/BaseBlock.php
  src/Model/BlockInterface.php
  src/Util/RecursiveBlockIterator.php
  tests/Util/RecursiveBlockIteratorIteratorTest.php
Labels: patch
