Repository sonata-project/SonataBlockBundle, pull requests merged in 2023-03, with the labels that each got.

#1140 DevKit updates for 4.x branch
  .github/workflows/lint.yaml
  .github/workflows/qa.yaml
  .github/workflows/symfony-lint.yaml
  .github/workflows/test.yaml
  Makefile
  composer.json
  rector.php
  src/Block/BlockContext.php
  src/Block/BlockContextManager.php
  src/Block/BlockLoaderChain.php
  src/Block/BlockRenderer.php
  src/Block/BlockServiceManager.php
  src/Block/Loader/ServiceLoader.php
  src/Block/Service/AbstractBlockService.php
  src/Block/Service/ContainerBlockService.php
  src/Block/Service/MenuBlockService.php
  src/Block/Service/RssBlockService.php
  src/Command/DebugBlocksCommand.php
  src/DependencyInjection/Configuration.php
  src/Event/BlockEvent.php
  src/Exception/Filter/DebugOnlyFilter.php
  src/Exception/Filter/IgnoreClassFilter.php
  src/Exception/Renderer/InlineDebugRenderer.php
  src/Exception/Renderer/InlineRenderer.php
  src/Exception/Strategy/StrategyManager.php
  src/Form/Type/ContainerTemplateType.php
  src/Form/Type/ServiceListType.php
  src/Meta/Metadata.php
  src/Model/BaseBlock.php
  src/Profiler/DataCollector/BlockDataCollector.php
  src/Templating/Helper/BlockHelper.php
  src/Twig/GlobalVariables.php
Labels: minor

#1142 Allow covariance in RecursiveBlockIterator
  composer.json
  src/Util/RecursiveBlockIterator.php
  src/Util/RecursiveBlockIteratorIterator.php
Labels: patch

#1152 Use Psalm 5
  composer.json
  psalm.xml
  src/Exception/Strategy/StrategyManager.php
  src/Form/Type/ContainerTemplateType.php
  src/Form/Type/ServiceListType.php
  src/Templating/Helper/BlockHelper.php
Labels: pedantic

#1153 Bump psalm to level 3
  psalm.xml
  src/DependencyInjection/Configuration.php
  src/Exception/Strategy/StrategyManager.php
  src/Templating/Helper/BlockHelper.php
  src/Util/RecursiveBlockIterator.php
  src/Util/RecursiveBlockIteratorIterator.php
Labels: pedantic

#1159 Add return types to FormMapper methods
  src/Form/Mapper/FormMapper.php
Labels: major
