Repository sonata-project/SonataBlockBundle, pull requests merged in 2023-05, with the labels that each got.

#1169 DevKit updates for 4.x branch
  .github/workflows/documentation.yaml
  .readthedocs.yaml
  docs/conf.py
  docs/cookbook/rapid_prototyping.rst
  docs/reference/advanced_usage.rst
  docs/reference/cache.rst
  docs/reference/events.rst
  docs/reference/exceptions.rst
  docs/reference/installation.rst
  docs/reference/profiler.rst
  docs/reference/provided_blocks.rst
  docs/reference/twig_helpers.rst
  docs/reference/your_first_block.rst
  docs/requirements.txt
Labels: automerge, dev-kit

#1170 Manual merge
  .github/workflows/documentation.yaml
  .github/workflows/lint.yaml
  .github/workflows/qa.yaml
  .github/workflows/symfony-lint.yaml
  .github/workflows/test.yaml
  .readthedocs.yaml
  composer.json
  docs/conf.py
  docs/cookbook/rapid_prototyping.rst
  docs/reference/events.rst
  docs/reference/exceptions.rst
  docs/reference/installation.rst
  docs/reference/profiler.rst
  docs/reference/provided_blocks.rst
  docs/reference/twig_helpers.rst
  docs/reference/your_first_block.rst
  docs/requirements.txt
Labels: pedantic

#1171 Up rector to 0.16
  composer.json
Labels: pedantic

#1172 Add support for form-extensions 2.0
  .github/workflows/test.yaml
  composer.json
  tests/App/Controller/DemoController.php
Labels: minor

#1173 Release 4.21.0
  CHANGELOG.md
Labels: dev-kit
