Repository sonata-project/SonataBlockBundle, pull requests merged in 2023-06, with the labels that each got.

#1174 Fix psalm and php-cs-fixer
  .php-cs-fixer.dist.php
  tests/Resources/XliffValidatorTestCase.php
Labels: pedantic

#1175 DevKit updates for 4.x branch
  .github/FUNDING.yml
Labels: automerge, dev-kit

#1176 Remove xliff tests
  tests/Resources/XliffTest.php
  tests/Resources/XliffValidatorTestCase.php
Labels: pedantic

#1178 Upgrade rector to 0.17
  composer.json
Labels: pedantic

#1179 Create UPGRADE-5.0.md
  UPGRADE-5.0.md
Labels: major

#1177 Release 5.0.0-alpha-1
  CHANGELOG.md
Labels: dev-kit

#1181 DevKit updates for 4.x branch
  .github/ISSUE_TEMPLATE/Bug.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/auto-merge-dev-kit.yaml
  .github/workflows/documentation.yaml
  .github/workflows/lint.yaml
  .github/workflows/qa.yaml
  .github/workflows/symfony-lint.yaml
  .github/workflows/test.yaml
  .symfony.bundle.yaml
  CONTRIBUTING.md
  README.md
  docs/.doctor-rst.yaml
Labels: automerge, dev-kit

#1182 DevKit updates for 5.x branch
  .github/ISSUE_TEMPLATE/Bug.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/auto-merge-dev-kit.yaml
  .github/workflows/documentation.yaml
  .github/workflows/lint.yaml
  .github/workflows/qa.yaml
  .github/workflows/symfony-lint.yaml
  .github/workflows/test.yaml
  .symfony.bundle.yaml
  CONTRIBUTING.md
  README.md
  docs/.doctor-rst.yaml
Labels: automerge, dev-kit

#1183 Cleanup older upgrade files
  UPGRADE-4.0.md
  UPGRADE-4.x.md
  UPGRADE-5.x.md
Labels: pedantic
