Repository sonata-project/SonataBlockBundle, pull requests merged in 2024-06, with the labels that each got.

#1210 Bump rector
  composer.json
Labels: pedantic

#1211 DevKit updates for 5.x branch
  .github/workflows/documentation.yaml
  .github/workflows/lint.yaml
  .github/workflows/qa.yaml
  .github/workflows/symfony-lint.yaml
  .github/workflows/test.yaml
  src/DependencyInjection/Compiler/TweakCompilerPass.php
Labels: automerge, dev-kit

#1212 Solve internal class usage
  src/DependencyInjection/SonataBlockExtension.php
Labels: patch
