Repository sonata-project/SonataBlockBundle, pull requests merged in 2025-05, with the labels that each got.

#1231 DevKit updates for 6.x branch
  phpstan.neon.dist
Labels: automerge, dev-kit

#1230 DevKit updates for 5.x branch
  phpstan.neon.dist
Labels: automerge, dev-kit

#1232 Bump psalm and phpstan
  composer.json
  psalm.xml
  src/Templating/Helper/BlockHelper.php
  src/Util/RecursiveBlockIterator.php
  tests/Twig/Extension/BlockExtensionTest.php
Labels: minor

#1229 fixes BlockServiceTestCase
  docs/reference/testing.rst
Labels: docs

#1233 5.2.0
  CHANGELOG.md
Labels: pedantic

#1234 DevKit updates for 5.x branch
  .github/workflows/lint.yaml
  .github/workflows/qa.yaml
  .github/workflows/symfony-lint.yaml
  .github/workflows/test.yaml
  Makefile
Labels: automerge, dev-kit
